asm_macro.o: asm_macro.S
boot.o: boot.S multiboot.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
file_sys_driver.o: file_sys_driver.c file_sys_driver.h types.h lib.h \
  idt.h x86_desc.h keyboard.h terminal.h i8259.h asm_macro.h
i8259.o: i8259.c i8259.h types.h lib.h idt.h x86_desc.h keyboard.h \
  terminal.h asm_macro.h
idt.o: idt.c idt.h types.h x86_desc.h lib.h keyboard.h terminal.h i8259.h \
  asm_macro.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h idt.h keyboard.h \
  terminal.h i8259.h asm_macro.h debug.h tests.h rtc.h paging.h \
  file_sys_driver.h
keyboard.o: keyboard.c keyboard.h types.h x86_desc.h lib.h idt.h \
  terminal.h i8259.h asm_macro.h
lib.o: lib.c lib.h types.h idt.h x86_desc.h keyboard.h terminal.h i8259.h \
  asm_macro.h
paging.o: paging.c paging.h types.h x86_desc.h lib.h idt.h keyboard.h \
  terminal.h i8259.h asm_macro.h
rtc.o: rtc.c rtc.h types.h lib.h idt.h x86_desc.h keyboard.h terminal.h \
  i8259.h asm_macro.h
terminal.o: terminal.c terminal.h types.h lib.h idt.h x86_desc.h \
  keyboard.h i8259.h asm_macro.h
tests.o: tests.c tests.h x86_desc.h types.h terminal.h lib.h idt.h \
  keyboard.h i8259.h asm_macro.h rtc.h file_sys_driver.h
